const bugsWithNamesPack = [
  { src: require("../images/bugs-with-names/adrian.jpg") },
  { src: require("../images/bugs-with-names/alex.jpg") },
  { src: require("../images/bugs-with-names/anastasia.jpg") },
  { src: require("../images/bugs-with-names/billy.jpg") },
  { src: require("../images/bugs-with-names/carlos.jpg") },
  { src: require("../images/bugs-with-names/charles.jpg") },
  { src: require("../images/bugs-with-names/dennis.jpg") },
  { src: require("../images/bugs-with-names/edith.jpg") },
  { src: require("../images/bugs-with-names/edward.jpg") },
  { src: require("../images/bugs-with-names/felicia.jpg") },
  { src: require("../images/bugs-with-names/frank.jpg") },
  { src: require("../images/bugs-with-names/gregory.jpg") },
  { src: require("../images/bugs-with-names/hailey.jpg") },
  { src: require("../images/bugs-with-names/hank.jpg") },
  { src: require("../images/bugs-with-names/hector.jpg") },
  { src: require("../images/bugs-with-names/ivan.jpg") },
  { src: require("../images/bugs-with-names/jesus.jpg") },
  { src: require("../images/bugs-with-names/joe.jpg") },
  { src: require("../images/bugs-with-names/jordan.jpg") },
  { src: require("../images/bugs-with-names/juanito.jpg") },
  { src: require("../images/bugs-with-names/julian.jpg") },
  { src: require("../images/bugs-with-names/lenny.jpg") },
  { src: require("../images/bugs-with-names/linus.jpg") },
  { src: require("../images/bugs-with-names/martha.jpg") },
  { src: require("../images/bugs-with-names/noah.jpg") },
  { src: require("../images/bugs-with-names/peter.jpg") },
  { src: require("../images/bugs-with-names/primrose.jpg") },
  { src: require("../images/bugs-with-names/robert.jpg") },
  { src: require("../images/bugs-with-names/sabrina.jpg") },
  { src: require("../images/bugs-with-names/sheldon.jpg") },
  { src: require("../images/bugs-with-names/stacy.jpg") },
  { src: require("../images/bugs-with-names/sylvia.jpg") },
  { src: require("../images/bugs-with-names/thomas.jpg") },
  { src: require("../images/bugs-with-names/viktoria.jpg") },
];

export default bugsWithNamesPack;
